# Generated by Django 2.1.1 on 2018-09-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180831_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name_plural': '数据'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': '标签'},
        ),
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
